[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python init_db.py check || echo 'Database check skipped'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

